### Update a new Patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name" : "Charles Jenkins",
  "address": "Cottbus, Germany",
  "dateOfBirth": "1979-12-01"
}

###